### ISSUE TITLE
unicode chars in yaml files preventing run

### ISSUE THREAD

**Issue by styk-tv** [awslabs/aws-serverless-ember#1]
awesome guide, going through the motions, however unicode detected in template prevents from run

```
aws cloudformation package --template-file api.yaml –-output-template-file api-deploy.yaml --s3-bucket ember-serverless-hosting-codebucket-30t6181l768l

Traceback (most recent call last):
  File "/Users/polfilm/builds/venv_containers/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/Users/polfilm/builds/venv_containers/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/Users/polfilm/builds/venv_containers/lib/python2.7/site-packages/awscli/clidriver.py", line 56, in main
    return driver.main()
  File "/Users/polfilm/builds/venv_containers/lib/python2.7/site-packages/awscli/clidriver.py", line 227, in main
    err.write(six.text_type(e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 17: ordinal not in range(128)
```

any ideas as to how to bypass?

**Comment by styk-tv** [comment]
haha (double dash not both dash)

```
–-output-template-file
```

please update blog entry, i guess i should have followed github readme instead.

**Comment by mlabieniec** [comment]
@styk-tv thanks for the heads up on that. I updated the blog post and fixed the character issue.
